# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            YONK
tagline:          being techie isn't enough
description:      "Memories can fade"
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /

author:
  name:           'YONK'
  url:            https://twitter.com/yonkyunior

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karloespiritu/blackdoc
